import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';
import { X } from 'lucide-react';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';

interface SalesItem {
  item_id: string;
  quantity: string;
  rate: string;
  amount: number;
}

const CreateSalesInvoice = () => {
  const { toast } = useToast();
  const queryClient = useQueryClient();
  
  const [customerId, setCustomerId] = useState('');
  const [referenceNo, setReferenceNo] = useState('');
  const [saleDate, setSaleDate] = useState(new Date().toISOString().split('T')[0]);
  const [narration, setNarration] = useState('');
  const [salesItems, setSalesItems] = useState<SalesItem[]>([
    { item_id: '', quantity: '', rate: '', amount: 0 }
  ]);

  const { data: customers } = useQuery({
    queryKey: ['customers-sales'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('customers')
        .select('id, customer_name')
        .order('customer_name');
      if (error) throw error;
      return data;
    },
  });

  const { data: items } = useQuery({
    queryKey: ['items-sales'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('items')
        .select('*')
        .order('product_code');
      if (error) throw error;
      return data;
    },
  });

  const { data: customerPricing } = useQuery({
    queryKey: ['customer-pricing', customerId],
    queryFn: async () => {
      if (!customerId) return [];
      const { data, error } = await supabase
        .from('customer_products')
        .select('item_id, price')
        .eq('customer_id', customerId);
      if (error) throw error;
      return data;
    },
    enabled: !!customerId,
  });

  const createSalesMutation = useMutation({
    mutationFn: async () => {
      if (!customerId) throw new Error('Customer is required');
      if (salesItems.some(item => !item.item_id || !item.quantity || !item.rate)) {
        throw new Error('All item fields must be filled');
      }

      const totalAmount = salesItems.reduce((sum, item) => sum + item.amount, 0);

      // Create order (order_number auto-generated by DB trigger)
      const { data: orders, error: orderError } = await supabase
        .from('orders')
        .insert([{
          customer_id: customerId,
          total_amount: totalAmount,
          status: 'approved',
        } as any])
        .select();

      if (orderError) throw orderError;
      const order = orders[0];

      // Insert order items
      const itemsToInsert = salesItems.map(item => ({
        order_id: order.id,
        item_id: item.item_id,
        quantity: parseFloat(item.quantity),
        unit_price: parseFloat(item.rate),
      }));

      const { error: itemsError } = await supabase
        .from('order_items')
        .insert(itemsToInsert);

      if (itemsError) throw itemsError;

      return order;
    },
    onSuccess: (order) => {
      queryClient.invalidateQueries({ queryKey: ['orders'] });
      toast({
        title: 'Success',
        description: `Sales invoice ${order.order_number} created successfully`,
      });
      resetForm();
    },
    onError: (error: Error) => {
      toast({
        title: 'Error',
        description: error.message,
        variant: 'destructive',
      });
    },
  });

  const resetForm = () => {
    setCustomerId('');
    setReferenceNo('');
    setSaleDate(new Date().toISOString().split('T')[0]);
    setNarration('');
    setSalesItems([{ item_id: '', quantity: '', rate: '', amount: 0 }]);
  };

  const addSalesItem = () => {
    setSalesItems([...salesItems, { item_id: '', quantity: '', rate: '', amount: 0 }]);
  };

  const removeSalesItem = (index: number) => {
    if (salesItems.length > 1) {
      setSalesItems(salesItems.filter((_, i) => i !== index));
    }
  };

  const updateSalesItem = (index: number, field: keyof SalesItem, value: string) => {
    const newItems = [...salesItems];
    newItems[index] = { ...newItems[index], [field]: value };
    
    if (field === 'item_id') {
      // Auto-fill rate from customer pricing
      const pricing = customerPricing?.find(p => p.item_id === value);
      if (pricing) {
        newItems[index].rate = pricing.price.toString();
      }
    }
    
    if (field === 'quantity' || field === 'rate') {
      const quantity = parseFloat(newItems[index].quantity) || 0;
      const rate = parseFloat(newItems[index].rate) || 0;
      newItems[index].amount = quantity * rate;
    }
    
    setSalesItems(newItems);
  };

  const calculateGrandTotal = () => {
    return salesItems.reduce((sum, item) => sum + item.amount, 0);
  };

  const handleSubmit = () => {
    createSalesMutation.mutate();
  };

  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === 'a' || e.key === 'A') {
      e.preventDefault();
      handleSubmit();
    } else if (e.key === 'q' || e.key === 'Q') {
      e.preventDefault();
      resetForm();
    }
  };

  return (
    <div className="min-h-screen bg-[#F5F5DC]" onKeyDown={handleKeyPress}>
      {/* Tally Header */}
      <div className="bg-[#1e40af] text-white px-4 py-2 flex items-center justify-between">
        <div className="flex items-center gap-4">
          <span className="font-bold text-lg">Tally <span className="text-yellow-400">GOLD</span></span>
          <span className="text-sm">Prime</span>
        </div>
        <div className="text-sm">
          {new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: '2-digit' })}
        </div>
      </div>

      {/* Sub Header */}
      <div className="bg-white border-b px-4 py-1 text-sm">
        Accounting Voucher Creation
      </div>

      {/* Voucher Type Bar */}
      <div className="bg-[#1e40af] text-white px-4 py-1 flex items-center justify-between">
        <span className="font-semibold">Sales</span>
        <button 
          onClick={resetForm}
          className="hover:bg-blue-700 px-2 py-0.5 rounded text-sm"
        >
          <X className="h-4 w-4" />
        </button>
      </div>

      {/* Main Form */}
      <div className="p-6 max-w-6xl mx-auto">
        <div className="bg-white border-2 border-gray-300 p-6 space-y-4">
          {/* Header Fields */}
          <div className="grid grid-cols-2 gap-6">
            <div className="space-y-1">
              <Label className="text-xs">Reference No</Label>
              <Input
                value={referenceNo}
                onChange={(e) => setReferenceNo(e.target.value)}
                className="h-8 bg-white border-gray-400"
                placeholder="Enter reference"
              />
            </div>
            <div className="space-y-1">
              <Label className="text-xs">Date</Label>
              <Input
                type="date"
                value={saleDate}
                onChange={(e) => setSaleDate(e.target.value)}
                className="h-8 bg-white border-gray-400"
              />
            </div>
          </div>

          {/* Customer Details */}
          <div className="space-y-3 border-t pt-3">
            <div className="grid grid-cols-[120px_1fr] gap-2 items-center">
              <Label className="text-sm">Party A/c name</Label>
              <Select
                value={customerId}
                onValueChange={setCustomerId}
              >
                <SelectTrigger className="h-8 bg-white border-gray-400">
                  <SelectValue placeholder="Select customer" />
                </SelectTrigger>
                <SelectContent>
                  {customers?.map((customer) => (
                    <SelectItem key={customer.id} value={customer.id}>
                      {customer.customer_name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>

          {/* Items Table */}
          <div className="border-t pt-4">
            <table className="w-full">
              <thead>
                <tr className="bg-gray-100 border-y">
                  <th className="text-left p-2 text-sm font-semibold">Name of Item</th>
                  <th className="text-right p-2 text-sm font-semibold w-28">Quantity</th>
                  <th className="text-right p-2 text-sm font-semibold w-32">Rate per</th>
                  <th className="text-right p-2 text-sm font-semibold w-32">Amount</th>
                  <th className="w-10"></th>
                </tr>
              </thead>
              <tbody>
                {salesItems.map((item, index) => (
                  <tr key={index} className="border-b">
                    <td className="p-1">
                      <Select
                        value={item.item_id}
                        onValueChange={(value) => updateSalesItem(index, 'item_id', value)}
                      >
                        <SelectTrigger className="h-8 bg-amber-50 border-gray-400">
                          <SelectValue placeholder="Select item" />
                        </SelectTrigger>
                        <SelectContent>
                          {items?.map((itm) => (
                            <SelectItem key={itm.id} value={itm.id}>
                              {itm.product_code} - {itm.product_name}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                    </td>
                    <td className="p-1">
                      <Input
                        type="number"
                        min="0.01"
                        step="0.01"
                        value={item.quantity}
                        onChange={(e) => updateSalesItem(index, 'quantity', e.target.value)}
                        className="h-8 text-right bg-white border-gray-400"
                        placeholder="0"
                      />
                    </td>
                    <td className="p-1">
                      <Input
                        type="number"
                        min="0.01"
                        step="0.01"
                        value={item.rate}
                        onChange={(e) => updateSalesItem(index, 'rate', e.target.value)}
                        className="h-8 text-right bg-white border-gray-400"
                        placeholder="0.00"
                      />
                    </td>
                    <td className="p-1">
                      <Input
                        value={item.amount.toFixed(2)}
                        readOnly
                        className="h-8 text-right bg-gray-50 border-gray-400 font-semibold"
                      />
                    </td>
                    <td className="p-1 text-center">
                      {salesItems.length > 1 && (
                        <button
                          onClick={() => removeSalesItem(index)}
                          className="text-red-600 hover:text-red-800"
                        >
                          <X className="h-4 w-4" />
                        </button>
                      )}
                    </td>
                  </tr>
                ))}
                <tr>
                  <td colSpan={5} className="p-1">
                    <button
                      onClick={addSalesItem}
                      className="text-blue-600 hover:text-blue-800 text-sm underline"
                    >
                      + Add Item
                    </button>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>

          {/* Narration */}
          <div className="border-t pt-4">
            <Label className="text-sm mb-2 block">Narration:</Label>
            <Textarea
              value={narration}
              onChange={(e) => setNarration(e.target.value)}
              className="bg-white border-gray-400 min-h-[60px]"
              placeholder="Additional notes..."
            />
          </div>

          {/* Total */}
          <div className="flex justify-end border-t pt-4">
            <div className="text-right space-y-1">
              <div className="text-sm text-gray-600">Total Amount:</div>
              <div className="text-2xl font-bold">₹{calculateGrandTotal().toFixed(2)}</div>
            </div>
          </div>
        </div>
      </div>

      {/* Action Bar */}
      <div className="fixed bottom-0 left-0 right-0 bg-gray-100 border-t flex items-center justify-between px-4 py-2 text-sm">
        <div className="flex gap-6">
          <button 
            onClick={resetForm}
            className="hover:bg-gray-200 px-2 py-1 rounded"
          >
            <span className="underline">Q</span>: Quit
          </button>
          <button 
            onClick={handleSubmit}
            className="hover:bg-gray-200 px-2 py-1 rounded"
            disabled={createSalesMutation.isPending}
          >
            <span className="underline">A</span>: {createSalesMutation.isPending ? 'Saving...' : 'Accept'}
          </button>
          <button className="hover:bg-gray-200 px-2 py-1 rounded">
            <span className="underline">X</span>: Cancel Vch
          </button>
        </div>
      </div>
    </div>
  );
};

export default CreateSalesInvoice;
